
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ORG_DOMAIN}}
  name: updatechannelconfig
spec:
  backoffLimit: 1
  template:
    metadata:
      name: updatechannelconfig
    spec:
      restartPolicy: "Never"
      containers:
      - name: updatechannelconfig
        image: hyperledger/fabric-tools:1.4.1
        command: 
        - /bin/sh
        - -c
        - |
          set -xe
          cd /shared;
          peer channel update -f ${UPDATED_ENVELOPE_PB} -c ${CHANNEL_NAME} -o ${ORDERER_ADDRESSES} --tls --cafile ${ORDERER_CA}
          RETURN_CODE=$?
          if [ $RETURN_CODE -eq "0" ]
          then
            echo 'Success signconfigtx'
          else
            echo 'Failed signconfigtx'
          fi
        env:
        - name: CORE_PEER_LOCALMSPID
          value: {{ORG_NAME}}MSP
        - name: CORE_PEER_LOCALMSPNAME
          value: {{ORG_NAME}}MSP
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /shared/crypto-config/peerOrganizations/{{ORG_DOMAIN}}/peers/peer0.{{ORG_DOMAIN}}/tls/ca.crt
        - name: CORE_PEER_MSPCONFIGPATH
          value: /shared/crypto-config/peerOrganizations/{{ORG_DOMAIN}}/users/admin/msp/
        - name: ORDERER_CA
          value: /shared/crypto-config/ordererOrganizations/{{ORDERER_DOMAIN}}/orderers/orderer0-{{ORDERER_NAME}}.{{ORDERER_DOMAIN}}/msp/tlscacerts/tlsca.{{ORDERER_DOMAIN}}-cert.pem
        - name: CORE_PEER_ADDRESS
          value: peer0-{{ORG_NAME}}.{{ORG_DOMAIN}}:7051
        - name: ORDERER_ADDRESSES
          value: orderer0-{{ORDERER_NAME}}.{{ORDERER_DOMAIN}}:7050
        - name: CHANNEL_NAME
          value: {{CHANNEL_NAME}}
        - name: UPDATED_ENVELOPE_PB
          value: config-update-in-envelope.pb
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: CORE_LOGGING_LEVEL
          value: DEBUG
        - name: CORE_PEER_ID
          value: cli
        - name: CORE_PEER_NETWORKID
          value: cli
        volumeMounts:
          - name: crypto-config
            mountPath: /shared
      volumes:
      - name: crypto-config
        nfs:
          server: {{EFS_SERVER}}
          path: {{PVS_PATH}}/{{EFS_PATH}}/{{EFS_EXTEND}}/akc-ca-data
